version: '3'
services:
  pgdb:
    image: "postgres:13.5"
    container_name: "pgdb"
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user_123"
    ports:
      - "54321:5432"
    volumes:
      - /home/project/db/data:/var/lib/postgresql/data
#      - ./migrations:/docker-entrypoint-initdb.d
#    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  task:
    container_name: "task"
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - pgdb
